### ISSUE TITLE
 Uncaught exception on thread "WindowsNativeRunloopThread" (#21) java.lang.NoSuchMethodError: <init>

### ISSUE THREAD

**Issue by petio** [LordAkkarin/Beacon#28]
Insert a clear and concise description of the issue you are experiencing.

**Reproduction Steps**
java -jar Beacon.jar

**Expected Behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - Application Version: Native Bytecode Version: 60.0

**Additional Context**
Uncaught exception on thread "WindowsNativeRunloopThread" (#21)
java.lang.NoSuchMethodError: <init>
        at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method) ~[Beacon.jar:?]
        at com.sun.glass.ui.Screen.initScreens(Screen.java:412) ~[Beacon.jar:?]
        at com.sun.glass.ui.Application.lambda$run$1(Application.java:152) ~[Beacon.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[Beacon.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[Beacon.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by dotStart** [comment]
This looks like you are running a version of Java that may be too new for your respective version of Beacon (Bytecode Version 60 implies Java 16 which is not supported in any of the stable releases).

Generally, I'd recommend upgrading to the latest alpha release of 3.0 which may be found [here](https://github.com/dotStart/Beacon/releases). An overview of the compatible Java versions can be found in the [documentation](https://dotstart.github.io/Beacon/docs/troubleshooting/java-version.html).

If the issue persists, please make sure to include the following in your bug report:

* Your operating System
* Beacon Version (to be found either on the page that you downloaded it from or in the Application Splash Screen)

**Comment by petio** [comment]
yes thank you with java 17 its ok, but the gateway rejected the UPnP request
